/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EpisodeInput = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'publishedDate' : IDL.Text,
  'published' : IDL.Bool,
  'explicit' : IDL.Bool,
  'audioFileId' : IDL.Text,
  'description' : IDL.Text,
  'artworkFileId' : IDL.Text,
  'showNotes' : IDL.Text,
});
export const Episode = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'publishedDate' : IDL.Text,
  'published' : IDL.Bool,
  'createdAt' : IDL.Int,
  'explicit' : IDL.Bool,
  'audioFileId' : IDL.Text,
  'description' : IDL.Text,
  'artworkFileId' : IDL.Text,
  'showNotes' : IDL.Text,
});
export const PodcastInfo = IDL.Record({
  'websiteUrl' : IDL.Text,
  'description' : IDL.Text,
  'author' : IDL.Text,
  'language' : IDL.Text,
  'category' : IDL.Text,
  'stationName' : IDL.Text,
});

export const idlService = IDL.Service({
  'createEpisode' : IDL.Func([EpisodeInput], [IDL.Nat], []),
  'deleteEpisode' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllEpisodes' : IDL.Func([], [IDL.Vec(Episode)], ['query']),
  'getEpisode' : IDL.Func([IDL.Nat], [IDL.Opt(Episode)], ['query']),
  'getEpisodes' : IDL.Func([], [IDL.Vec(Episode)], ['query']),
  'getPodcastInfo' : IDL.Func([], [PodcastInfo], ['query']),
  'getRssFeed' : IDL.Func([], [IDL.Text], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'setPodcastInfo' : IDL.Func([PodcastInfo], [], []),
  'updateEpisode' : IDL.Func([IDL.Nat, EpisodeInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EpisodeInput = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'publishedDate' : IDL.Text,
    'published' : IDL.Bool,
    'explicit' : IDL.Bool,
    'audioFileId' : IDL.Text,
    'description' : IDL.Text,
    'artworkFileId' : IDL.Text,
    'showNotes' : IDL.Text,
  });
  const Episode = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'publishedDate' : IDL.Text,
    'published' : IDL.Bool,
    'createdAt' : IDL.Int,
    'explicit' : IDL.Bool,
    'audioFileId' : IDL.Text,
    'description' : IDL.Text,
    'artworkFileId' : IDL.Text,
    'showNotes' : IDL.Text,
  });
  const PodcastInfo = IDL.Record({
    'websiteUrl' : IDL.Text,
    'description' : IDL.Text,
    'author' : IDL.Text,
    'language' : IDL.Text,
    'category' : IDL.Text,
    'stationName' : IDL.Text,
  });
  
  return IDL.Service({
    'createEpisode' : IDL.Func([EpisodeInput], [IDL.Nat], []),
    'deleteEpisode' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllEpisodes' : IDL.Func([], [IDL.Vec(Episode)], ['query']),
    'getEpisode' : IDL.Func([IDL.Nat], [IDL.Opt(Episode)], ['query']),
    'getEpisodes' : IDL.Func([], [IDL.Vec(Episode)], ['query']),
    'getPodcastInfo' : IDL.Func([], [PodcastInfo], ['query']),
    'getRssFeed' : IDL.Func([], [IDL.Text], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'setPodcastInfo' : IDL.Func([PodcastInfo], [], []),
    'updateEpisode' : IDL.Func([IDL.Nat, EpisodeInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };