/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Episode {
  'id' : bigint,
  'title' : string,
  'duration' : string,
  'publishedDate' : string,
  'published' : boolean,
  'createdAt' : bigint,
  'explicit' : boolean,
  'audioFileId' : string,
  'description' : string,
  'artworkFileId' : string,
  'showNotes' : string,
}
export interface EpisodeInput {
  'title' : string,
  'duration' : string,
  'publishedDate' : string,
  'published' : boolean,
  'explicit' : boolean,
  'audioFileId' : string,
  'description' : string,
  'artworkFileId' : string,
  'showNotes' : string,
}
export interface PodcastInfo {
  'websiteUrl' : string,
  'description' : string,
  'author' : string,
  'language' : string,
  'category' : string,
  'stationName' : string,
}
export interface _SERVICE {
  'createEpisode' : ActorMethod<[EpisodeInput], bigint>,
  'deleteEpisode' : ActorMethod<[bigint], boolean>,
  'getAllEpisodes' : ActorMethod<[], Array<Episode>>,
  'getEpisode' : ActorMethod<[bigint], [] | [Episode]>,
  'getEpisodes' : ActorMethod<[], Array<Episode>>,
  'getPodcastInfo' : ActorMethod<[], PodcastInfo>,
  'getRssFeed' : ActorMethod<[], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'setPodcastInfo' : ActorMethod<[PodcastInfo], undefined>,
  'updateEpisode' : ActorMethod<[bigint, EpisodeInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];